---
title: Lecture Data Science for Electron Microscopy Winter 2024
author:
  - name: Philipp Pelz
    orcid: 0000-0002-8009-4515
    corresponding: true
    email: philipp.pelz@fau.de
    roles:
      - Investigation
      - Project administration
      - Software
      - Visualization
    affiliations:
      - FAU Erlangen-Nuernberg
keywords:
  - Data Science
  - Electron Microscopy
abstract: |
  This is the website for the Data Science for Electron Microscopy Lecture
plain-language-summary: |
  This is the website for the Data Science for Electron Microscopy Lecture
key-points:
  - a website for the lecture
date: last-modified
bibliography: references.bib
citation:
  container-title: Friedrich-Alexander Universitaet Erlangen-Nuernberg
number-sections: true
jupyter: python3
---
- [Pelz Lab website](https://pelzlab.science)
- [Studon Link](https://www.studon.fau.de/campo/course/421992)
- [Link to Github folder](https://github.com/ECLIPSE-Lab/DataScienceForElectronMicroscopy)





## Lecture 1: Intro (25.10.2024)
<!-- @marrero2019 -->
- Introduction 
- [d2l Chapter 2: Preliminaries](https://d2l.ai/chapter_preliminaries/index.html)

## Lecture 2: Regression and Sensor Fusion (8.11.2024) {#sec-lecture2}

- [d2l Chapter 3: Regression](https://d2l.ai/chapter_linear-regression/index.html)
- Sensor Fusion Slides

## Lecture 3: CNNs (15.11.2024) {#sec-lecture3}

- [d2l Chapter 7: CNNs](https://d2l.ai/chapter_convolutional-neural-networks/index.html)
- [d2l Chapter 8: CNNs](https://d2l.ai/chapter_convolutional-modern/index.html)

## Lecture 4: Classification, Segmentation, AutoEncoders (22.11.2024) {#sec-lecture4}

- [d2l Chapter 4: Classification](https://d2l.ai/chapter_linear-classification/index.html)
- [d2l Chapter 14.9: Segmentation](https://d2l.ai/chapter_computer-vision/semantic-segmentation-and-dataset.html)
- Segmentation
- Dimensionality Reduction
  - PCA
  - Autoencoder
  - Variational Autoencoder

## Miniproject (29.11. - 13.12.2024) {#sec-lecture5}

In the miniproject, you will test multiple deep neural network architectures on one of four microscopy-related tasks.
You should summarize your results in a short presentation (5 minutes + 2 minutes discussion) and deliver a Jupyter Notebook with your code and results.
The miniproject will be graded and will count as 40% towards your final grade.

1. Segmentation Task

    We will use the HRTEM dataset from "A robust synthetic data generation framework for machine learning in high-resolution transmission electron microscopy (HRTEM)" by @rangel2024robust to implement a segmentation model.
    The goal is to segment nanoparticles in HRTEM images.

    Please use the article  "A robust synthetic data generation framework for machine learning in high-resolution transmission electron microscopy (HRTEM)" by @rangel2024robust as a starting point for your implementation.

    The datast contains pairs of HRTEM images and ground truth segmentations. 

2. VAE & Dimensionality Reduction

    We will use the dataset from "Uncovering material deformations via machine learning combined with four-dimensional scanning transmission electron microscopy" by @shi2022uncovering to implement a dimensionality reduction model and cluster 4DSTEM data.

    The goal is to learn a mapping from 4DSTEM data to a lower-dimensional embedding where you can perform clustering to identify different deformation modes.

    Please use the article  "Uncovering material deformations via machine learning combined with four-dimensional scanning transmission electron microscopy" by @shi2022uncovering as a starting point for your implementation.    

3. Denoising

    We will use the dataset from "Unsupervised deep denoising for four-dimensional scanning transmission electron microscopy" by @sadri2024unsupervised to implement a denoising model for 4DSTEM data. 
    
    The goal is to learn a mapping from noisy to clean 4DSTEM data.

    Please use the article  "Unsupervised deep denoising for four-dimensional scanning transmission electron microscopy" by @sadri2024unsupervised as a starting point for your implementation.

    The article contains pytorch code for the model. 
    
    Learn how to adapt it to your needs and try to replicate the results on the SrTiO3_High_mag_Low_dose.npy and SrTiO3_High_mag_High_dose.npy datasets.

4. Image-to-Image Translation

    We will use a simulated X-ray image dataset with pairs of projected thickness and phase contrast images to implement an Image to image translation model. 
    
    The goal is to learn a mapping from phase contrast images to projected thickness images. 
    
    This is usually a task that is solved with multiple measurements and a physical model of the imaging process. 
    
    Here we will try to learn this mapping from simulated data. 
    Please use the article "Multi-resolution convolutional neural networks for inverse problems" by @wang2020multi as a starting point for your implementation.

## Lecture 5: Mixed Bag (10.1.2025)  {#sec-lecture6}

- Project presentations
- Generative Adversarial Networks

## Lecture 6: Gaussian Processes Introduction (17.1.2025) {#sec-lecture7}

- Introduction to Gaussian Processes  

## Lecture 7: Gaussian Processes Applications (24.1.2025) {#sec-lecture8}

- Bayesian Optimization
- Active Learning
- Deep Kernel Learning

## Lecture 8: Inverse Imaging Problems 1: Linear Problems (31.1.2025) {#sec-lecture9}

- Algorithms for linear inverse problems
- Tomography
- Deconvolution

## Lecture 9: Inverse Imaging Problems 2: Nonlinear Problems (7.2.2025) {#sec-lecture10}

- Phase Contrast Imaging
- Superresolution Imaging
- Inverse Problems in Electron Microscopy

## References {.unnumbered}

::: {#refs}
:::